services:
  api01: &api
    image: slyte/projetopizza:latest
    hostname: api01
    #build:
    #  dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_HTTP_PORTS=3001
      - DB_HOST=host.docker.internal
      - DB_USER=pizzaiolo
      - DB_PASSWORD=pizzaPassword
      - DB_PORT=5434
      - DB_NAME=pizza
    expose:
      - "3001"
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          cpus: "0.225"
          memory: "0.90GB"
  api02:
    <<: *api
    image: slyte/projetopizza:latest
    hostname: api02
    depends_on:
      - db
    environment:
      - ASPNETCORE_HTTP_PORTS=3002
      - DB_HOST=host.docker.internal
      - DB_USER=pizzaiolo
      - DB_PASSWORD=pizzaPassword
      - DB_PORT=5434
      - DB_NAME=pizza
    expose:
      - "3002"
    ports:
      - "3002:3002"
    deploy:
      resources:
        limits:
          cpus: "0.225"
          memory: "0.90GB"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "0.20GB"
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=pizzaPassword
      - POSTGRES_USER=pizzaiolo
      - POSTGRES_DB=pizza
    expose:
      - "5434"
    ports:
      - "5434:5434"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -p 5434
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1.0GB"
networks:
  default:
    driver: bridge
    name: projeto-pizza-net